//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitGray.WebAPIRecargas.Services
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using BitGray.WebAPIRecargas.Models;
    
    public partial class BDRecargasEntities : DbContext
    {
        public BDRecargasEntities()
            : base("name=BDRecargasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Consumo> Consumoes { get; set; }
        public DbSet<Parametro> Parametros { get; set; }
        public DbSet<Recarga> Recargas { get; set; }
        public DbSet<Saldo> Saldos { get; set; }
    }
}
