//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitGray.WebAPIRecargas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumo
    {
        public long idConsumo { get; set; }
        public long idParametro { get; set; }
        public string celular { get; set; }
        public int consumo1 { get; set; }
        public System.DateTime fechaConsumo { get; set; }
    }
}
