//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitGray.WebAPIRecargas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recarga
    {
        public long idRecargas { get; set; }
        public long idParametros { get; set; }
        public string celular { get; set; }
        public int valor { get; set; }
        public System.DateTime fechaVigencia { get; set; }
        public System.DateTime fechaRecarga { get; set; }
    }
}
